### ISSUE TITLE
Store a reference to the line number for a token

### ISSUE THREAD

**Issue by andrewebdev** [niklasfasching/go-org#107]
When dealing with the AST, there are some cases where we need to report syntax or other errors back to the user. This is hard, when all we have is the node, without any Idea where in the document the error occurred.

Would it be feasible store a reference on every node in the tree that will indicate the _line number_ (and potentially column number) where that node was found?

**Comment by niklasfasching** [comment]
Related to #91. 
Since nodes are implemented as different structs, adding position data to nodes is quite a bit of busy work. The suggestion (2) (keeping a map[node]range on the document to look up the position associated with a node) should be simple enough though. Would that be enough for your use case?

**Comment by niklasfasching** [comment]
Feel free to re-open if you get back to this
