### ISSUE TITLE
How to get inline markup to work?

### ISSUE THREAD

**Issue by prosoitos** [niklasfasching/go-org#29]
Is inline highlighting supported? (My apologies if the information is already posted somewhere.)

With markdown, inline highlighting is possible with backticks.

In regular org export, it can be achieved with `src_lang{text}` or `src_lang[:eval no]{text}`. But this does not seem to work here (this code gets exported verbatim).

Similarly, to get custom inline formatting in markdown, it is possible to insert inline raw html:
```md
Some text <span style=xxxx>custom formatted text</span>.
```

In regular org export, inline html works with the `@@` syntax, so this works:
```org
Some text @@html:<span style=xxxx>@@custom formatted text@@html:</span>@@.
```

But in Hugo, this is also rendered verbatim.

Am I missing something? is this not supported? if so, are there workarounds?

Thank you!!!

**Comment by prosoitos** [comment]
I guess one workaround is to have the entire sentence in html:

```org
#+BEGIN_export html
Some text<span style=xxx>custom formatted text</span>.
#+END_export
```

**Comment by prosoitos** [comment]
Another thing which is not working inline (unless I am doing something wrong) are blank spaces.

In regular org export, `&nbsp;` works (and in markdown where inline html is supported, `<br>` does the trick).

So it seems that any inline markup fails.

**Comment by niklasfasching** [comment]
should be fixed by https://github.com/niklasfasching/go-org/commit/4b56810a6561e8ec253fe97d6d6bdd2ab1b308f8 and https://github.com/niklasfasching/go-org/commit/3018ace8d0179fb23847ddb47aaa91d7c7b6b279. 

non-breaking spaces are supported in the form of org [html entities](https://github.com/niklasfasching/go-org/blob/4b56810a6561e8ec253fe97d6d6bdd2ab1b308f8/org/html_entity.go#L207), i.e. `/nbsp`. 

`&nbsp;` seems to export as `<p>&amp;nbsp;</p>` in regular export for me, so I won't add support for it - but please correct me if I'm wrong :).

**Comment by prosoitos** [comment]
Great!! Thank you for all your work! :slightly_smiling_face: 

I will try things out in the coming days/weeks.

In the mean time, as workarounds, I created a bunch of shortcodes that were allowing me to get some inline markup. But this is a lot nicer! :slightly_smiling_face:
