### ISSUE TITLE
lines interpreted as comments

### ISSUE THREAD

**Issue by ilohmar** [niklasfasching/go-org#41]
It seems that go-org interprets all lines matching "^\\s*#" as comments.  That has two flaws, one straight-forward, one a bit more subtle:

1. Org Mode only treats "^\\s*#\\s" lines are comments.

2. In special blocks like BEGIN_CENTER (same w/ SRC, VERBATIM etc), there are no such comments.  I am not sure how this is handled, and exactly what blocks are affected etc.

**Comment by niklasfasching** [comment]
1. fixed in https://github.com/niklasfasching/go-org/commit/c025db7bddb71179314f20934b46f9dc67db2f43
2. not sure about this one. is there a benefit to not supporting comments in blocks? Special blocks whose contents we want to be treated as literal text are already [exempt from any parsing](https://github.com/niklasfasching/go-org/blob/c025db7bddb71179314f20934b46f9dc67db2f43/org/block.go#L53). Other blocks can contain all kinds of org elements (e.g. images, tables) - is the value in excluding comments?

**Comment by ilohmar** [comment]
Great, thanks!

Re 2., I am also not sure, and do not even particularly care, I just noted the behavior in the "native" org-export.  Come to think of it, it doesn't make much sense to me (as many of the arcane details of the still-beloved org-mode ;).  So I am perfectly fine with the way go-org handles these blocks.

**Comment by niklasfasching** [comment]
Cool, I'll leave (2) then until someone comes up with a use case for it.
