### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by improve100** [niklasfasching/go-org#47]
$ ./go-org org blorg build
Unsupported command: org

$ ./go-org blorg build
Error: lstat content: no such file or directory

$ ./go-org blorg serve
2021/01/18 20:45:50 listening on: :3000
2021/01/18 20:46:03 lstat content: no such file or directory

$ ./go-org blorg build
Error: lstat content: no such file or directory

**Comment by niklasfasching** [comment]
will look into improving the docs and errors.

**Comment by niklasfasching** [comment]
Fixed the error messages naming the command org instead of go-org and a little more but not much else. When go 1.16 drops with embed I'll change the generated `blorg.org` and `content/` of `blorg init` to  [blorg testdata](https://github.com/niklasfasching/go-org/blob/02df432d763cf4746e03832e7750e085876f538e/blorg/testdata/blorg.org). Until then just take a look at those files. 
If you just want something that works I'd stick to [hugo](https://gohugo.io/) - I didn't put much love into blorg and stopped as soon as it worked well enough for my specific use case.

**Comment by niklasfasching** [comment]
https://github.com/niklasfasching/go-org/commit/7030666/
