### ISSUE TITLE
Blorg reder org files to index.html

### ISSUE THREAD

**Issue by e-eight** [niklasfasching/go-org#69]
I am trying to use blorg, instead of hugo, since it seems simple enough for my purposes. Is there any way to to tell blorg to render `content/xyz.org` to `public/xyz/index.html` instead of `public/xyz.html`? Looking at the source code it seems like that can be modified to make it work this way. But I am not very proficient in `go`, so I was wondering if there are any options that control that behavior.

**Comment by niklasfasching** [comment]
It's possible and I wanted the same but doing so breaks links - a relative link from `xyz.org` referencing `xyz.png` would incorrectly look for the image at `xyz/xyz.png`. 

Would this be useful to you anyways?

**Comment by e-eight** [comment]
Well I prefer not to have the `.html` extension be visible, so it's more of a matter of aesthetics for me than actual utility. Currently I am writing my posts as `xyz/index.org`, which while it is a little cumbersome, does the work.

**Comment by niklasfasching** [comment]
I'm doing the same and I can't think of a clean alternative; as said, just rendering `content/xyz.org` into `public/xyz/index.html` rather than `content/xyz.html` breaks relative links. `content/img.png` would be accessible as `img.png` from `xyz.org` but not from `public/xyz/index.html` (which would try to open `public/xyz/img.png` instead of the correct `public/img.png`). 

Closing for now unless we can come up for a solution to that problem.
