### ISSUE TITLE
[FEATURE REQUEST] Support :PROPERTIES: :END: at top of file and then #+KEY: frontmatter block

### ISSUE THREAD

**Issue by wakatara** [niklasfasching/go-org#93]
At the moment, the frontmatter block of `#+KEY: VALUE` needs to reside at the top of the page in order to be picked up by the Hugo static site generator. 

However, a lot of people are using `org-roam` to link generate content for blog posts, which requires a 
``` org-mode
:PROPERTIES:
:ID: hash
:END: 
```
at the top of the page in order for it to be findable and linkable by org-roam

It would be great if go-org could support the PROPERTIES block at the top, then followed by the KEY Value front matter so this could be `ln -s` directly to the `content/posts` directory in Hugo.

**Comment by niklasfasching** [comment]
Hey, thx for the easy to understand request. It sounds very reasonable, but I think you need to open the request again with hugo.

It's been some time since I looked at hugo but I think this cannot be done in go-org (please correct me if i'm wrong); hugo only sends [the part of the document it considers frontmatter](https://github.com/gohugoio/hugo/blob/0d1161b2639d240f3720b5c5b3c90789d162fbb4/parser/pageparser/pagelexer_intro.go#L138-L140) (i.e. all lines starting with `#+` at the top of the file) to go-org for [parsing](https://github.com/gohugoio/hugo/blob/0d1161b2639d240f3720b5c5b3c90789d162fbb4/parser/pageparser/pageparser.go#L76).

I think [`lexFrontMatterOrgMode`](https://github.com/gohugoio/hugo/blob/0d1161b2639d240f3720b5c5b3c90789d162fbb4/parser/pageparser/pagelexer_intro.go#L115) would need to be changed for your request

**Comment by wakatara** [comment]
Done, I've put it over in https://github.com/gohugoio/hugo/issues/10639 , so let's see if they can implement it. I may wade into the code and give it a go myself and do a PR. I can't imagine this is a tough one to fix.

**Comment by wakatara** [comment]
(and by the way, thanks for the quick response and very helpful next steps! As well as all your hard work on this project. I was really happy to find out I could use org-mode to post right in Hugo. Pretty awesome!).

**Comment by niklasfasching** [comment]
thx! this means a lot :)
