### ISSUE TITLE
Possibility to extract the parser into it's own package?

### ISSUE THREAD

**Issue by andrewebdev** [niklasfasching/go-org#98]
I'm wondering if it's feasible to extract the parser that generates the AST into it's own package?

I'm working on a project where I only need the AST for the org document. We then pass that node tree to a separate app that can output multiple different formats, not just HTML.

(I know it's not a big deal to include the writer, I can just import the bits I need from `go-org`, so this is more just a question regarding the feasibility of separating the two)

**Comment by niklasfasching** [comment]
Hi! 

I guess we could pull out the (org & html) writer implementations into a separate package - the writer interface would have to stay in the org package if we want to keep `document.Write`... and I guess there's other ways to slice things. 

So re "is this feasible": Probably? :D  

Could you give some more context on what value you see in splitting the package? I don't want to dismiss this outright, but since this would break public API (e.g. `org.NewHTMLWriter`) I'd err on the side of not doing it unless there's something I'm missing

**Comment by niklasfasching** [comment]
Feel free to re-open in case you look into this again
